[build]
  publish = "dist/"
  functions = "functions"

[functions]
  directory = "src"
  included_files = ["src/api/**/*", "public/**/*"]

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
