[build]
  publish = "dist/"
  functions = "functions"

[functions]
  directory = "src"
  included_files = ["src/api/**/*", "public/**/*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
